[package]
name = "biona_macros"
version = "0.1.0"
authors = ["nikolaykolevk <nikolaykolevk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.42"
quote = "1.0.7"

[lib]
proc-macro = true
